config/routes.rb
SongArchive::Application.routes.draw do
  
  devise_for :users, :path_prefix => 'd', :controllers => { :registrations => "registrations" }
  resources :users
  
  resources :nav_items

  resources :pages

  resources :songs
  match "songs/tag/:id" => "songs#tag"

  
  root :to => 'pages#default'

end

app/models/nav_item.rb
class NavItem < ActiveRecord::Base
  # Nav items form a tree hierarchy
  has_ancestry
  
  # If the nav item is destroyed and it relates to a page, the page must also be deleted
  # (otherwise it can't be accessed)
  has_one :page, :dependent => :destroy
  
  #Initialize the model with a priority
  after_initialize :default_values
  
  # Priority must be an integer
  validates :priority, :numericality => { :only_integer => true }
  validates :title, :presence => true
  
  # Realpath is the path where clicking the nav item should take the user.
  # The nav item can either relate to a page or have an explicitly defined path.
  # If it's  associated with a page, the realpath is the path to the page.
  # Otherwise it's the path explicitly defined by the user.
  def realpath
    if(self.page)
      return Rails.application.routes.url_helpers.page_path(self.page)
    end
    '/' + self.explicit_path
  end
  
  def self.default_page
    # By default the first path of the first level of navigation is used as default page
    default_page = NavItem.order("priority").roots[0]
    if default_page
      return default_page.realpath
    else
      # If there's nothign in the nav, take the user to create some pages
      return pages_path
    end
  end
  
  # Give a default priority of 0
  def default_values
    self.priority ||= 0
    rescue ActiveModel::MissingAttributeError
      # This can be safely ignored: error is thrown only when NavItem.exists?() is called, because the
      # priority field isn't fetched
  end
  
end

app/controllers/nav_items_controller.rb
class NavItemsController < ApplicationController
  # Only admins can make changes to nav items
  before_filter :require_admin
  
  # GET /nav_items
  # GET /nav_items.json
  def index
    @nav_items = NavItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nav_items }
    end
  end

  # GET /nav_items/new
  # GET /nav_items/new.json
  def new
    @nav_item = NavItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nav_item }
    end
  end

  # GET /nav_items/1/edit
  def edit
    @nav_item = NavItem.find(params[:id])
  end

  # POST /nav_items
  # POST /nav_items.json
  def create
    @nav_item = NavItem.new(extract_item(params))

    respond_to do |format|
      if @nav_item.save
        format.html { redirect_to nav_items_path, notice: t('nav_items.created') }
        format.json { render json: @nav_item, status: :created, location: @nav_item }
      else
        format.html { render action: "new" }
        format.json { render json: @nav_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nav_items/1
  # PUT /nav_items/1.json
  def update
    @item = NavItem.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(extract_item(params))
        format.html { redirect_to nav_items_url, notice: t('nav_items.saved') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nav_items/1
  # DELETE /nav_items/1.json
  def destroy
    @item = NavItem.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to nav_items_url, notice: t('nav_items.destroyed') }
      format.json { head :no_content }
    end
  end
  
  private
  
  def extract_item(hash)
    item = hash[:nav_item][:nav_item]
    item[:explicit_path] = hash[:nav_item][:explicit_path]
    item
  end
end

app/views/nav_items/_fields.html.erb
<%= form.fields_for(:nav_item, @nav_item) do |f| %>
  <%= render :partial => 'general/errors', :locals => { :model => @nav_item } %>

  <div class="field required">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :parent %>
    <%= f.select :parent_id, nav_items_options(@nav_item) %>
  </div>
  <div class="field">
    <%= f.label :priority %>
    <%= f.text_field :priority %>
  </div>
<% end %>

app/views/nav_items/_form.html.erb
<%= form_for(@nav_item) do |f| %>
<%= render :partial => 'fields',
           :locals => {:form => f} %>
  <div class="field required">
    <%= f.label :explicit_path %>
    <%= f.text_field :explicit_path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nav_items/edit.html.erb
<h1><%= t 'nav_items.edit' %></h1>

<%= render 'form' %>

<%= link_to t('actions.back'), nav_items_path %>

app/views/nav_items/index.html.erb
<h1><%= t 'nav_items.list' %></h1>

<div class="actions">
  <%= link_to t('nav_items.new'), new_nav_item_path %>
</div>

<table>
  <tr>
    <th><%= t 'nav_items.title' %></th>
    <th></th>
    <th></th>
  </tr>

<% @nav_items.each do |item| %>
  <tr>
    <td><%= item.title %></td>
    <td><%= link_to t('actions.edit'), edit_nav_item_path(item) %></td>
    <td><%= link_to t('actions.destroy'), item, confirm: t('nav_items.confirm_destroy'), method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/nav_items/new.html.erb
<h1><%= t 'nav_items.new' %></h1>

<%= render 'form' %>

<%= link_to t('actions.back'), nav_items_path %>