config/routes.rb
SongArchive::Application.routes.draw do
  
  devise_for :users, :path_prefix => 'd', :controllers => { :registrations => "registrations" }
  resources :users
  
  resources :nav_items

  resources :pages

  resources :songs
  match "songs/tag/:id" => "songs#tag"

  
  root :to => 'pages#default'

end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :name, :presence => true
  validates :lyrics, :presence => true
  
  # The songs can be tagged
  acts_as_taggable
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # Only logged-in users can view, add, edit or delete songs.
  # Admin rights are not required for any action relating to songs.
  before_filter :require_login
  
  # GET /songs
  # GET /songs.json
  def index
    # Display all songs and tag list
    @songs = Song.order("name")
    @tags = Song.tag_counts_on(:tags)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end
  
  def tag
    # Display songs for given tags and tag list
    @tagname = params[:id]
    @songs = Song.tagged_with(@tagname).order("name")
    @tags = Song.tag_counts_on(:tags)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    # Display the given song
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    # Create a new song and display the edit form
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    # Find the given song for editing
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    # Create the song from the given data
    @song = Song.new(params[:song])
    # Make the given keywords tags
    @song.tag_list = @song.keywords

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: t('songs.created') }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])
    # Set the tags
    @song.tag_list = params[:song][:keywords]

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: t('songs.saved') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url, notice: t('songs.destroyed') }
      format.json { head :no_content }
    end
  end
end

app/helpers/songs_helper.rb
module SongsHelper
    include ActsAsTaggableOn::TagsHelper
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <%= render :partial => 'general/errors', :locals => { :model => @song } %>

  <h2><%= t('activerecord.attributes.song.basic_information')%></h2>
  <div class="field required">
    <%= f.label :name %>
    <%= f.text_field :name, size: 50 %>
  </div>
  <div class="field">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, cols: 60, rows: 10 %>
  </div>
  <div class="field">
    <%= f.label :melody %>
    <%= f.text_field :melody, size: 50 %>
  </div>
  <div class="field">
    <%= f.label :lyrics_author %>
    <%= f.text_field :lyrics_author %>
  </div>
    <div class="field">
    <%= f.label :songbook_number %>
    <%= f.text_field :songbook_number, size: 5 %>
  </div>
  <div class="field">
    <%= f.label :keywords %>
    <%= f.text_field :keywords, size: 50 %>
  </div>
    <div class="field required">
    <h2><%= f.label :lyrics %></h2>
    <%= f.text_area :lyrics, cols: 60, rows: 20 %>
  </div>
  <div class="field">
   <h2> <%= f.label :extra_lyrics %></h2>
    <%= f.text_area :extra_lyrics, cols: 60, rows: 20 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/_songlist.html.erb
<div id= "tagcloud">
<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
  <%= link_to tag.name, { :action => :tag, :id => tag.name }, :class => css_class %>
  <% end %>
 </div>

<div class="songlist">
<ul>
<% @songs.each do |song| %>
  <li>
    <%= link_to song.name, song %>
  </li>
<% end %>
</ul>

</div>

app/views/songs/edit.html.erb
<h1><%=t 'songs.edit' %></h1>

<%= render 'form' %>

<%= link_to t('actions.back'), @song %>

app/views/songs/index.html.erb
<h1><%= t 'songs.archive' %></h1>

<%= link_to t('songs.new'), new_song_path %>

<%= render "songlist" %>

app/views/songs/new.html.erb
<h1><%=t 'songs.new' %></h1>

<%= render 'form' %>

<%= link_to t('actions.back'), songs_path %>

app/views/songs/show.html.erb
<div>
  <h1><%= @song.name %></h1>
<%= link_to t('actions.edit'), edit_song_path(@song) %> |
<%= link_to t('actions.destroy'), @song, confirm: t('songs.confirm_destroy'), method: :delete %>
</div>

<div id ='columns'>
<div id="song">
<p>
  <%= simple_format @song.lyrics %>
</p>

<p>
  <b><%= t('activerecord.attributes.song.extra_lyrics')%>:</b>
  <% if(@song.extra_lyrics.length > 0) %>
    <%= simple_format @song.extra_lyrics %>
  <% else %>
    <div class="empty">Ei lisäsäkeistöjä</div>
  <% end %>
</p>

<%= link_to t('actions.back'), songs_path %>
</div>

<div id="information">
<p>
  <b><%= t('activerecord.attributes.song.introduction')%>:</b>
  <%= @song.introduction %>
</p>

<p>
  <b><%= t('activerecord.attributes.song.melody')%>:</b>
  <%= @song.melody %>
</p>

<p>
  <b><%= t('activerecord.attributes.song.lyrics_author')%>:</b>
  <%= @song.lyrics_author %>
</p>

<p>
  <b><%= t('activerecord.attributes.song.songbook_number')%>:</b>
  <%= @song.songbook_number %>
</p>

<p>
  <b><%= t('activerecord.attributes.song.keywords')%>:</b>
  <%= @song.keywords %>
</p>
</div>
</div>

app/views/songs/tag.html.erb
<h1><%= t'songs.for_tag', :tag => @tagname %></h1>

<%= render "songlist" %>