config/routes.rb
SongArchive::Application.routes.draw do
  
  devise_for :users, :path_prefix => 'd', :controllers => { :registrations => "registrations" }
  resources :users
  
  resources :nav_items

  resources :pages

  resources :songs
  match "songs/tag/:id" => "songs#tag"

  
  root :to => 'pages#default'

end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <%= render :partial => 'general/errors', :locals => { :model => @page } %>
  <h2><%= t('activerecord.attributes.page.page')%></h2>
  <div class="field required">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field required">
    <%= f.label :content %>
    <%= f.text_area :content, cols: 100, rows: 20 %>
  </div>
  <h2><%= t('activerecord.attributes.page.navigation')%></h2>
  <%= render :partial => 'nav_items/fields',
            :locals => {:form => f} %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1><%= t('pages.edit') %></h1>

<%= render 'form' %>

<%= link_to t('actions.show'), @page %> |
<%= link_to t('actions.back'), pages_path %>

app/views/pages/index.html.erb
<h1><%= t('pages.list') %></h1>

<div class="actions">
  <%= link_to t('pages.new'), new_page_path %>
</div>

<table>
  <tr>
    <th><%= t('activerecord.attributes.page.title') %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= link_to t('actions.show'), page %></td>
    <td><%= link_to t('actions.edit'), edit_page_path(page) %></td>
    <td><%= link_to t('actions.destroy'), page, confirm: t('pages.confirm_destroy'), method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/pages/new.html.erb
<h1> <%= t('pages.new') %></h1>

<%= render 'form' %>

<%= link_to t('actions.back'), pages_path %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>

<% if user_signed_in? && current_user.is_admin %>
  <div>
  <%= link_to t('actions.edit'), edit_page_path(@page) %> |
  <%= link_to t('actions.all_pages'), pages_path %>
  </div>
<% end %>

<%= raw @page.content %>