config/routes.rb
SongArchive::Application.routes.draw do
  
  devise_for :users, :path_prefix => 'd', :controllers => { :registrations => "registrations" }
  resources :users
  
  resources :nav_items

  resources :pages

  resources :songs
  match "songs/tag/:id" => "songs#tag"

  
  root :to => 'pages#default'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xml:lang="fi" lang="fi" xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta charset="utf-8" />
  <title>Sitsipakki</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body class="nav-depth-<%=@nav.size%>">
	<div id="wrapper">
	
		<header>
			<div class="header">
				<ul>
				  <% if user_signed_in? %>
				    <li><%= link_to(t('devise.ui.my_account'), edit_user_registration_path) %></li>
						<li><%= link_to(t('devise.ui.sign_out'), destroy_user_session_path, :method => :delete) %></li>
				  <% else %>
				    <li><%= link_to(t('devise.ui.sign_up'), new_user_registration_path)  %></li>
				    <li><%= link_to(t('devise.ui.sign_in'), new_user_session_path)  %></li>
				  <% end %>
				</ul>
			</div>
	
			<div class="navigation">
    			<%= raw menu(@nav, @nav_item_crumb) %>
			</div>
		</header>
	
		<div id="content">
		  <% if user_signed_in? && current_user.is_admin %>
		    <div id="admin-nav">
		      <%= t 'admin_nav.title' %>:
		      <%= link_to t('admin_nav.pages'), pages_path %> |
		      <%= link_to t('admin_nav.navigation'), nav_items_path %> |
          <%= link_to t('admin_nav.users'), users_path %>
		    </div>
		  <% end %>
      <% if alert %>
        <p class="flash-error"><%= alert %></p>
      <% end %>
      <% if notice %>
        <p class="flash-notice"><%= notice %></p>
      <% end %>

	    <%= yield %>
	  </div>

		<footer>
		</footer>

	</div>
</body>
</html>